# golangci-lint configuration for Claude Agent SDK Go
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []
  exclude-dirs:
    - examples  # Examples are for demonstration, not production code

linters:
  default: none
  enable:
    # Essential - must pass
    - govet        # Official Go tool
    - staticcheck  # Advanced static analysis
    - unused       # Find unused code
    - ineffassign  # Detect ineffectual assignments

    # Important
    - misspell     # Spelling mistakes
    - gosec        # Security issues

  settings:
    govet:
      enable-all: true
      disable:
        - shadow         # too many false positives
        - fieldalignment # micro-optimization
        - printf         # disabled due to bug with Go 1.25.x
        - unusedwrite    # too strict for struct initialization patterns

    staticcheck:
      checks:
        - all
        - "-SA1012"  # nil context is ok in tests
        - "-S1009"   # len nil check is fine

    misspell:
      locale: US
      ignore-words:
        - cancelled  # MCP protocol uses British spelling

    gosec:
      severity: high
      confidence: high
      excludes:
        - G104  # unhandled errors - covered by errcheck
        - G304  # file path from variable - needed for SDK
        - G204  # subprocess with variable - needed for SDK
        - G306  # file permissions - tests need 0755

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/victorarias/claude-agent-sdk-go

output:
  formats:
    text:
      path: stdout
  sort-order:
    - file
    - linter
